// Asset minification and hosting/security configuration, generated from src/data.js
// so the Content-Security-Policy always matches what the site actually loads.
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { site } from './data.js';
import { assetVersion, themeBootHash } from './lib.js';

const SRC = join(dirname(fileURLToPath(import.meta.url)), 'assets');
const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

export async function buildAssets(out) {
  let esbuild = null;
  try {
    esbuild = await import('esbuild');
  } catch {
    console.warn('esbuild not installed: writing unminified CSS/JS (run `npm install` for production builds).');
  }
  for (const [name, dir, loader] of [['styles.css', 'css', 'css'], ['main.js', 'js', 'js']]) {
    const source = readFileSync(join(SRC, name), 'utf8');
    const code = esbuild
      ? (await esbuild.transform(source, { loader, minify: true, target: ['chrome90', 'safari15', 'firefox90', 'edge90'] })).code
      : source;
    mkdirSync(join(out, 'assets', dir), { recursive: true });
    writeFileSync(join(out, 'assets', dir, name), code);
    assetVersion[loader] = createHash('sha256').update(code).digest('hex').slice(0, 10);
  }
}

function csp() {
  const connect = ["'self'"];
  const script = ["'self'", `'${themeBootHash}'`];
  const img = ["'self'", 'data:'];
  if (site.ga4) {
    script.push('https://www.googletagmanager.com');
    connect.push('https://*.google-analytics.com', 'https://*.analytics.google.com', 'https://www.googletagmanager.com');
    img.push('https://*.google-analytics.com', 'https://www.googletagmanager.com');
  }
  if (site.metaPixel) {
    script.push('https://connect.facebook.net');
    connect.push('https://www.facebook.com');
    img.push('https://www.facebook.com');
  }
  if (site.formEndpoint) connect.push(new URL(site.formEndpoint).origin);
  return [
    "default-src 'self'",
    `script-src ${script.join(' ')}`,
    "style-src 'self'",
    "font-src 'self'",
    `img-src ${img.join(' ')}`,
    `connect-src ${connect.join(' ')}`,
    'frame-src https://www.google.com',
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "frame-ancestors 'none'",
    "manifest-src 'self'",
    'upgrade-insecure-requests',
  ].join('; ');
}

export const securityHeaders = () => ({
  'Content-Security-Policy': csp(),
  'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), payment=(), usb=(), interest-cohort=()',
  'Cross-Origin-Opener-Policy': 'same-origin',
  'Cross-Origin-Resource-Policy': 'same-origin',
  'X-Permitted-Cross-Domain-Policies': 'none',
});

const cacheRules = [
  ['/assets/css/*', 'public, max-age=31536000, immutable'],
  ['/assets/js/*', 'public, max-age=31536000, immutable'],
  ['/assets/fonts/*', 'public, max-age=31536000, immutable'],
  ['/assets/img/*', 'public, max-age=604800'],
];

export function writeDeployFiles(out) {
  const h = securityHeaders();

  // Netlify & Cloudflare Pages
  writeFileSync(
    join(out, '_headers'),
    `/*\n${Object.entries(h).map(([k, v]) => `  ${k}: ${v}`).join('\n')}\n\n` +
      cacheRules.map(([p, v]) => `${p}\n  Cache-Control: ${v}`).join('\n\n') +
      '\n',
  );

  // Vercel
  writeFileSync(
    join(ROOT, 'vercel.json'),
    JSON.stringify(
      {
        buildCommand: 'npm run build',
        outputDirectory: 'public',
        trailingSlash: true,
        headers: [
          { source: '/(.*)', headers: Object.entries(h).map(([key, value]) => ({ key, value })) },
          ...cacheRules.map(([p, v]) => ({ source: p.replace('*', '(.*)'), headers: [{ key: 'Cache-Control', value: v }] })),
        ],
      },
      null,
      2,
    ) + '\n',
  );

  // Apache / cPanel (most Kenyan shared hosting)
  writeFileSync(
    join(out, '.htaccess'),
    `# Generated by src/deploy.js — edit src/data.js and rebuild instead of editing this file.
Options -Indexes
ErrorDocument 404 /404.html
DirectoryIndex index.html

<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteCond %{HTTPS} off
  RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
  RewriteCond %{HTTP_HOST} ^www\\.(.+)$ [NC]
  RewriteRule ^ https://%1%{REQUEST_URI} [L,R=301]
</IfModule>

<IfModule mod_headers.c>
${Object.entries(h).map(([k, v]) => `  Header always set ${k} "${v.replace(/"/g, '\\"')}"`).join('\n')}
  <FilesMatch "\\.(css|js|woff2)$">
    Header set Cache-Control "public, max-age=31536000, immutable"
  </FilesMatch>
  <FilesMatch "\\.(png|jpg|webp|ico|svg)$">
    Header set Cache-Control "public, max-age=604800"
  </FilesMatch>
  <FilesMatch "\\.html$">
    Header set Cache-Control "public, max-age=0, must-revalidate"
  </FilesMatch>
</IfModule>

<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/css application/javascript application/json image/svg+xml text/xml application/xml text/plain application/rss+xml
</IfModule>

AddType font/woff2 .woff2
AddType application/manifest+json .webmanifest
`,
  );

  // security.txt (RFC 9116)
  const expires = new Date(Date.now() + 365 * 864e5).toISOString().replace(/\.\d+Z$/, 'Z');
  mkdirSync(join(out, '.well-known'), { recursive: true });
  writeFileSync(
    join(out, '.well-known', 'security.txt'),
    `Contact: mailto:${site.email}\nContact: tel:${site.phoneE164}\nExpires: ${expires}\nPreferred-Languages: en, sw\nCanonical: ${site.url}/.well-known/security.txt\nPolicy: ${site.url}/legal-notice/#security\n`,
  );
}
