export const glossary = [
  ['A/B testing', 'Comparing two versions of an ad, page or message to see which performs better with real users.'],
  ['AI Overviews', 'AI-generated summaries Google shows at the top of some search results, citing web sources.'],
  ['Bounce rate', 'The share of visitors who leave a page without interacting further. In GA4 this is the inverse of engagement rate.'],
  ['Call to action (CTA)', 'The specific next step you ask someone to take, such as “Chat on WhatsApp” or “Book a free audit”.'],
  ['Citation (local SEO)', 'Any online mention of your business name, address and phone number, such as a directory listing.'],
  ['Click-through rate (CTR)', 'Clicks divided by impressions. A high CTR means your ad or search listing is compelling.'],
  ['Content calendar', 'A schedule of what will be published, where and when.'],
  ['Conversion', 'A valuable action such as a call, WhatsApp chat, form submission or purchase.'],
  ['Conversion rate', 'Conversions divided by visitors or clicks.'],
  ['Conversion rate optimization (CRO)', 'Improving pages, offers and flows so a higher share of visitors become leads or customers.'],
  ['Core Web Vitals', 'Google’s measurements of loading speed, responsiveness and visual stability.'],
  ['Cost per click (CPC)', 'What you pay on average for each ad click.'],
  ['Cost per lead (CPL)', 'Total marketing spend divided by the number of leads generated.'],
  ['Customer acquisition cost (CAC)', 'Total cost to win one new paying customer.'],
  ['Customer lifetime value (LTV)', 'The total profit a customer brings over the whole relationship.'],
  ['Engagement rate', 'Interactions (likes, comments, shares, saves) relative to reach or followers.'],
  ['Entity', 'A clearly defined thing — such as a business, person or place — that search engines and AI models can recognise and describe.'],
  ['Funnel', 'The stages a buyer moves through: awareness, consideration, conversion and loyalty.'],
  ['GA4', 'Google Analytics 4, Google’s free analytics platform for websites and apps.'],
  ['GEO (Generative Engine Optimization)', 'Optimising your brand and content so AI assistants such as ChatGPT, Gemini, Perplexity and Google AI Overviews mention and cite you.'],
  ['Google Business Profile', 'Google’s free business listing that appears on Maps and in local search results.'],
  ['Hook', 'The first line or first second of content, designed to stop the scroll.'],
  ['Impressions', 'The number of times content or an ad was displayed.'],
  ['Keyword', 'A word or phrase people type into search engines.'],
  ['Landing page', 'A focused page built for one offer and one action, usually used with ads.'],
  ['Lead', 'A potential customer who has shown interest, e.g. by messaging, calling or filling a form.'],
  ['Lead magnet', 'A free resource or offer exchanged for contact details.'],
  ['llms.txt', 'A plain-text file at the root of a website that summarises the site for large language models.'],
  ['Local SEO', 'Optimisation to appear in location-based searches and Google Maps results.'],
  ['Map pack', 'The block of three local businesses shown with a map in Google results.'],
  ['Meta Pixel', 'Tracking code that reports website actions back to Facebook and Instagram ads.'],
  ['NAP', 'Name, Address, Phone — business details that should be identical everywhere online.'],
  ['Organic traffic', 'Visitors who arrive from unpaid search results.'],
  ['Pay-per-click (PPC)', 'Advertising where you pay each time someone clicks your ad.'],
  ['Reach', 'The number of unique people who saw your content.'],
  ['Retargeting', 'Showing ads to people who already visited your site, watched your videos or engaged with you.'],
  ['Return on ad spend (ROAS)', 'Revenue generated divided by ad spend.'],
  ['Schema markup', 'Structured data added to web pages that helps search engines and AI understand content.'],
  ['Search intent', 'The goal behind a search — to learn, compare or buy.'],
  ['SEO (Search Engine Optimization)', 'Improving a website so it ranks higher in unpaid search results.'],
  ['SERP', 'Search Engine Results Page.'],
  ['Spark Ads', 'TikTok ads that promote existing organic posts.'],
  ['UGC', 'User-generated content: authentic content made by customers or creators, often used in ads.'],
  ['UTM parameters', 'Tags added to links so analytics tools know which campaign sent the visitor.'],
];
