// Industry playbooks, free tools and the Academy course. Content here powers
// /industries/, /tools/, /academy/ and /resources/.

export const industries = [
  {
    slug: 'schools-colleges',
    story: 'It is early December. The principal of a Nakuru college watches the January intake form pile stay thin while a newer school down the road fills up. Parents are asking about fees in three WhatsApp groups, and nobody from the college is there. We put the college on every screen those parents look at: Google reviews from proud parents, Reels from sports day, an open-day campaign and a WhatsApp line that answers within the hour. By the first week of January, the tour slots are fully booked.',
    name: 'Schools & Colleges',
    icon: 'spark',
    hook: 'Fill every intake with parents and students who already trust you.',
    intro: 'Parents and students research schools for weeks before they visit. They read Google reviews, scroll your Facebook page, ask in WhatsApp groups and compare fees. We make sure your school is the one they keep seeing, and that every enquiry gets a fast, warm reply.',
    challenges: ['Enquiries spike around January, May and September intakes, then go quiet', 'Parents trust other parents more than adverts', 'Enquiries arrive on WhatsApp, calls and DMs and get lost'],
    playbook: [
      ['Google Business Profile', 'Photos of classrooms, labs and transport, plus a steady flow of parent reviews that mention results and safety.'],
      ['Open-day campaigns', 'Meta ads to parents aged 28–50 within your catchment, driving bookings for open days and school tours.'],
      ['Student-life video', 'Reels and TikToks of sports, clubs and results days that current parents love to share.'],
      ['Course & fees pages', 'SEO pages for every course or level, with fees ranges and intake dates, so you rank for “best schools in Nakuru”.'],
      ['WhatsApp follow-up', 'A labelled enquiry pipeline and follow-up scripts until the family visits or applies.'],
    ],
    kpis: ['Enquiries per intake', 'Cost per admission', 'Open-day bookings', 'Enquiry-to-admission rate'],
    idea: 'A “Day in the life” video series filmed by students, cut into Reels and run as ads two weeks before each intake.',
    faqs: [
      ['When should a school start marketing for the next intake?', 'Start 8–10 weeks before the intake. Build awareness first with video and reviews, then switch to open-day and application campaigns in the final four weeks.'],
      ['Can schools advertise on TikTok?', 'Yes, but target parents and adult learners. TikTok does not allow ads targeted at users under 18 in many regions, and parents usually make the decision anyway.'],
    ],
  },
  {
    slug: 'hotels-hospitality',
    story: 'A lodge near Lake Nakuru has stunning sunsets and empty rooms from Monday to Thursday. Every weekend booking arrives through a platform that keeps a slice of the money. We film the sunset, the breakfast and the fire pit, show them to Nairobi couples just after payday and add a “book direct on WhatsApp” button with a late-checkout perk. The phone starts buzzing on Tuesday, and the bookings stop paying commission.',
    name: 'Hotels, Lodges & Airbnbs',
    icon: 'heart',
    hook: 'More direct bookings, fewer commissions, fuller weekends.',
    intro: 'Lake Nakuru, Menengai, Naivasha and the Rift Valley draw visitors every weekend. Most of them choose where to stay on Google Maps, Instagram and TikTok, then book on WhatsApp. We help you win those bookings directly instead of paying commission on every one.',
    challenges: ['Heavy dependence on booking platforms and their commissions', 'Quiet midweek and low-season periods', 'Guests judge you on photos and reviews before anything else'],
    playbook: [
      ['Google Maps & reviews', 'A complete hotel listing, fresh photos and replies to every review on Google and TripAdvisor.'],
      ['Direct-booking offers', 'WhatsApp booking links and “book direct” perks such as late checkout or breakfast.'],
      ['Short video', 'Room tours, sunsets and food in Reels and TikToks, plus creator stays that bring their audiences.'],
      ['Nairobi weekenders', 'Ads targeted at Nairobi audiences for weekend and holiday packages, timed to paydays.'],
      ['Corporate & events', 'LinkedIn and Google ads for conferences, team-building and weddings.'],
    ],
    kpis: ['Direct bookings', 'Occupancy midweek', 'Cost per booking', 'Review rating'],
    idea: 'A “Payday Weekend” package launched every month-end with a 15-second TikTok and a WhatsApp broadcast to past guests.',
    faqs: [
      ['How do hotels get more direct bookings?', 'Make booking direct easy (WhatsApp link, clear rates), give a small perk for booking direct, and retarget people who viewed your rooms on Instagram or your website.'],
      ['Do creator stays work for lodges?', 'They do when the creator’s audience matches your guests. We pick creators by audience location and engagement, agree deliverables in writing, and track bookings with a unique code.'],
    ],
  },
  {
    slug: 'real-estate',
    story: 'A developer in Bahati gets 200 enquiries a month and closes almost none. The sales team spends its days calling people who were “just checking”. Meanwhile, a nurse in Leeds wants a plot back home but cannot visit. We add budget and timeline questions to the lead form, send drone videos and title-deed explainers, and invite diaspora buyers to a live virtual site visit. The calls get fewer, the conversations get serious, and the nurse pays her deposit from Leeds.',
    name: 'Real Estate & Construction',
    icon: 'pin',
    hook: 'Qualified buyers and site visits, including Kenyans abroad.',
    intro: 'Plots, apartments and homes are high-value decisions with long research cycles. Buyers in Nakuru, Nairobi and the diaspora want proof: title documents, video tours, progress updates and honest pricing. We build that trust online and filter out time-wasters before they reach your sales team.',
    challenges: ['Lots of enquiries, few serious buyers', 'Long decision cycles of weeks or months', 'Diaspora buyers need extra trust before paying'],
    playbook: [
      ['Qualified lead ads', 'Meta and Google lead forms with budget and timeline questions, so sales only call serious buyers.'],
      ['Video tours & updates', 'Drone footage, walk-throughs and monthly construction updates that build confidence.'],
      ['Diaspora campaigns', 'Targeted ads to Kenyans in the UK, USA, Canada and the Gulf, with webinar and virtual site-visit offers.'],
      ['Location SEO', 'Pages for “plots for sale in Nakuru”, Bahati, Njoro, Lanet and every area you sell in.'],
      ['Nurture on WhatsApp', 'Weekly updates to opted-in prospects until they are ready for a site visit.'],
    ],
    kpis: ['Qualified leads', 'Site visits booked', 'Cost per site visit', 'Sales closed'],
    idea: 'A monthly “Saturday Site Visit” with free transport from Nakuru CBD, promoted with lead ads and confirmed on WhatsApp.',
    faqs: [
      ['How do I reach Kenyans in the diaspora?', 'Target by location (for example UK, USA, Gulf states) combined with interests and language, and offer virtual site visits, video calls and clear payment plans.'],
      ['Are lead form ads good for real estate?', 'Yes, if you add qualifying questions. More friction means fewer but much better leads, which saves your sales team time.'],
    ],
  },
  {
    slug: 'healthcare-clinics',
    story: 'A family clinic in Milimani has excellent doctors and a waiting room that is half empty. Patients two streets away search “clinic near me” at 8pm and find someone else. We complete the Google profile with services, insurance and hours, publish simple health tips reviewed by the doctors, and open WhatsApp booking with reminders. Patients start to arrive saying, “I found you on Google, and you replied straight away.”',
    name: 'Clinics, Pharmacies & Wellness',
    icon: 'shield',
    hook: 'Become the trusted name patients search for, responsibly.',
    intro: 'Patients search “clinic near me”, “dentist in Nakuru” or “pharmacy open now”, then check reviews before they call. Healthcare marketing has to build trust while respecting professional advertising rules and patient privacy. We keep your marketing helpful, accurate and compliant.',
    challenges: ['Patients choose on reviews and convenience', 'Professional rules limit what you can claim in adverts', 'Health data is sensitive personal data under the Data Protection Act'],
    playbook: [
      ['Local SEO', 'A complete Google profile with services, hours, insurance accepted and photos of your facility.'],
      ['Health education', 'Simple articles and videos that answer common questions, reviewed by your clinicians.'],
      ['Appointment booking', 'WhatsApp and website booking with reminders that reduce no-shows.'],
      ['Reputation care', 'Polite, private responses to reviews that never disclose patient details.'],
      ['Compliant ads', 'Ads that promote services and access without guarantees or before-and-after claims that rules prohibit.'],
    ],
    kpis: ['Appointment requests', 'Calls from Google', 'No-show rate', 'Review rating'],
    idea: 'A monthly free health-check day (blood pressure, sugar) promoted on Google and Facebook, with WhatsApp booking.',
    faqs: [
      ['Can clinics run Facebook ads in Kenya?', 'Yes, within Meta’s health advertising policies and your professional body’s rules. Avoid promising outcomes, avoid targeting based on health conditions, and keep claims factual.'],
      ['How should we reply to a negative review?', 'Thank them, apologise for the experience, and invite them to contact you privately. Never confirm that the person is a patient or mention any details of their care.'],
    ],
  },
  {
    slug: 'restaurants-cafes',
    story: 'A café in Nakuru town is packed on Saturdays and quiet on Tuesdays. Its pancakes are the best in the area, but only regulars know it. We film the pancakes in slow motion, launch “Two-for-Tuesday” to people within three kilometres at lunchtime and invite guests to a WhatsApp list. Six weeks later, Tuesday has a queue.',
    name: 'Restaurants, Cafés & Bars',
    icon: 'play',
    hook: 'Full tables on Tuesday, not just on Friday.',
    intro: 'People decide where to eat on their phones: Google Maps, TikTok food videos, Instagram and delivery apps. We make your food look irresistible, fill quiet days with offers and turn first-time diners into regulars.',
    challenges: ['Busy weekends, empty weekdays', 'Competition from delivery apps and new spots', 'Food content needs to be fresh every week'],
    playbook: [
      ['Maps & menu', 'A Google listing with menu, prices, photos and “order online” links that rank for “restaurants near me”.'],
      ['Food video', 'Weekly Reels and TikToks: sizzling plates, behind the counter, staff favourites.'],
      ['Weekday offers', 'Tuesday and Wednesday deals promoted to people within a few kilometres, at lunch and after work.'],
      ['Customer content', 'A photo spot and a hashtag, then reposting guests’ content with permission.'],
      ['WhatsApp regulars', 'An opt-in list for specials, events and birthday treats.'],
    ],
    kpis: ['Directions requests', 'Weekday covers', 'Delivery orders', 'Repeat visits'],
    idea: '“Two-for-Tuesday” promoted with a 10-second TikTok and a WhatsApp Status countdown every Monday evening.',
    faqs: [
      ['Should restaurants be on TikTok?', 'Yes. Food is one of the most-watched categories. Short, well-lit clips of signature dishes and the people who make them work best.'],
      ['How do I get more Google reviews for my restaurant?', 'Put a QR code on the table and the bill folder, and have staff ask happy guests personally. Reply to every review.'],
    ],
  },
  {
    slug: 'retail-ecommerce',
    story: 'A fashion shop on Kenyatta Avenue posts new stock every day and gets fifty “price?” messages a week, but sales hardly move. Customers ask, wait, forget and scroll on. We put prices in the posts, set up a quick reply with price, delivery and M-Pesa details, film try-on videos and retarget everyone who watched them. The messages turn into payments, and buyers come back for the Friday drop.',
    name: 'Retail Shops & E-commerce',
    icon: 'target',
    hook: 'Turn scrollers into M-Pesa payments, online and in store.',
    intro: 'Whether you sell from a shop on Kenyatta Avenue or ship across Kenya, buyers discover products on Instagram, TikTok and Google, ask questions on WhatsApp and pay with M-Pesa. We connect every step so more browsers become buyers.',
    challenges: ['Lots of DMs asking “price?” that never buy', 'Rising ad costs', 'Customers buy once and disappear'],
    playbook: [
      ['Catalogues everywhere', 'Products with prices on WhatsApp Business, Instagram and Facebook shops.'],
      ['Creative that sells', 'UGC-style videos, unboxings and try-ons that answer questions before they are asked.'],
      ['Retargeting', 'Ads to people who viewed products, watched videos or messaged but did not buy.'],
      ['Fast replies', 'Quick replies with price, delivery and M-Pesa details so every DM gets an answer in seconds.'],
      ['Repeat sales', 'Broadcasts to opted-in customers for new stock, restocks and loyalty offers.'],
    ],
    kpis: ['Orders', 'Cost per purchase', 'DM-to-sale rate', 'Repeat customers'],
    idea: 'A weekly “New Drop Friday” with a TikTok reveal, a WhatsApp broadcast to past buyers and retargeting ads to video viewers.',
    faqs: [
      ['How do I stop “price?” DMs that never buy?', 'Show prices in posts and catalogues, use a quick reply that includes price, delivery and payment, and follow up once after 24 hours.'],
      ['Do I need a website to sell online in Kenya?', 'Not at first. Many shops start with WhatsApp catalogues and Instagram. A website helps you rank on Google and run better-tracked ads as you grow.'],
    ],
  },
  {
    slug: 'agribusiness-agrovets',
    story: 'An agrovet in Njoro stocks a new certified seed that could double a farmer’s harvest, but farmers trust what their neighbours plant. We film a local farmer using it from planting to harvest, post the story in Swahili on Facebook and YouTube, and start a WhatsApp advisory line before the long rains. By planting season, farmers walk in asking for “the seed from the video”.',
    name: 'Agribusiness & Agrovets',
    icon: 'chart',
    hook: 'Reach farmers where they really are: phones, groups and markets.',
    intro: 'Nakuru is one of Kenya’s farming heartlands. Farmers and agro-dealers use Facebook groups, YouTube, WhatsApp and local radio to compare seeds, feeds, inputs and equipment. We help agribusinesses build trust with practical content and turn it into orders and dealer enquiries.',
    challenges: ['Buyers trust word of mouth and demonstrations', 'Seasonal demand around planting and harvest', 'Mixed audiences: smallholders, large farms and dealers'],
    playbook: [
      ['Practical video', 'Demonstrations and farmer testimonials in Swahili and English on YouTube, Facebook and TikTok.'],
      ['Seasonal campaigns', 'Ads timed to the long and short rains, planting and harvest windows.'],
      ['WhatsApp advisory', 'An opt-in advisory line with tips that keeps your brand top of mind and drives orders.'],
      ['Dealer locator', 'Google Maps listings and a stockist page so farmers find your products nearby.'],
      ['Field-day promotion', 'Event promotion and follow-up for demo plots and field days.'],
    ],
    kpis: ['Orders and enquiries', 'Dealer sign-ups', 'Cost per lead', 'Field-day attendance'],
    idea: 'A “Shamba Results” series following one farmer from planting to harvest using your product, posted every two weeks.',
    faqs: [
      ['Do farmers really use social media?', 'Many do, especially Facebook, YouTube and WhatsApp, and they share useful content widely in groups. Practical, local-language video performs best.'],
      ['When should agrovets advertise?', 'Ramp up 2–4 weeks before the planting season in your area, then shift to crop-care and harvest products as the season progresses.'],
    ],
  },
  {
    slug: 'professional-services',
    story: 'A Nakuru accounting firm is brilliant at tax, but clients only find it through referrals, so growth depends on luck. Every January, business owners Google “tax help Nakuru” and call whoever shows up. We turn the partners’ advice into short LinkedIn videos, plain-English guides and a February tax-season webinar. Prospects now arrive having already watched three videos, and the first call starts with “we want to work with you.”',
    name: 'Professional Services & NGOs',
    icon: 'chat',
    hook: 'Turn expertise into enquiries from the right clients and partners.',
    intro: 'Law firms, accountants, consultants, SACCOs and NGOs win on credibility. Clients and partners Google you, check LinkedIn and read what you publish before they reach out. We turn your expertise into content and visibility that brings the right conversations.',
    challenges: ['Long, trust-based buying decisions', 'Professional rules on advertising for some fields', 'Partners and funders need evidence of impact'],
    playbook: [
      ['Expert content', 'Articles, guides and short videos that answer real client questions.'],
      ['LinkedIn presence', 'Leadership profiles, company page and thought-leadership posts on a steady rhythm.'],
      ['Service SEO', 'Pages that rank for the services and locations you cover.'],
      ['Impact storytelling', 'For NGOs and SACCOs: stories, data and reports that funders and members share.'],
      ['Lead nurture', 'Email newsletters and webinars that keep you top of mind until clients are ready.'],
    ],
    kpis: ['Qualified enquiries', 'Consultations booked', 'LinkedIn reach', 'Newsletter sign-ups'],
    idea: 'A monthly 30-minute LinkedIn Live or webinar answering clients’ top three questions, clipped into short videos afterwards.',
    faqs: [
      ['Can law firms in Kenya advertise?', 'Advocates must follow the Law Society of Kenya’s rules on publicity, which limit how services can be promoted. Educational content and a strong, factual online presence are usually the safest and most effective route.'],
      ['How do NGOs use digital marketing?', 'To show impact, recruit volunteers and partners, and raise funds. Clear stories with numbers and faces work far better than general awareness posts.'],
    ],
  },
];

export const tools = [
  {
    slug: 'marketing-grader',
    name: 'Digital Marketing Grader',
    icon: 'chart',
    hook: 'Score your online marketing out of 100 in two minutes and get your top fixes.',
    title: 'Free Digital Marketing Grader for Kenyan Businesses | Steff Cloud',
    description: 'Score your business’s digital marketing out of 100 in two minutes. Free grader for Kenyan businesses covering Google, reviews, social, ads, WhatsApp and tracking.',
  },
  {
    slug: 'whatsapp-link-generator',
    name: 'WhatsApp Link Generator',
    icon: 'chat',
    hook: 'Create a wa.me link with a pre-filled message for your bio, ads and posters.',
    title: 'Free WhatsApp Link Generator (wa.me) for Kenya | Steff Cloud',
    description: 'Create a free WhatsApp click-to-chat link with a pre-filled message. Works with Kenyan (07…, 01…) and international numbers. Use it in your bio and ads.',
  },
  {
    slug: 'marketing-budget-calculator',
    name: 'Marketing Budget Calculator',
    icon: 'calc',
    hook: 'Work out the leads you need, a starting ad budget and the right plan.',
    title: 'Free Marketing Budget Calculator for Kenyan Businesses | Steff Cloud',
    description: 'Calculate how many leads you need, a starting ad budget in KES and the right plan for your sales goal. Free marketing budget calculator for Kenyan businesses.',
  },
];

// Marketing grader questions: [id, area, question, weight, tip when not done]
export const graderQuestions = [
  ['gbp', 'Get found', 'Is your Google Business Profile verified, complete and updated in the last month?', 10, 'Complete and verify your Google Business Profile, add 20+ real photos and post an update every week.'],
  ['reviews', 'Get found', 'Do you have 20 or more Google reviews with an average of 4.5 stars or higher?', 8, 'Ask every happy customer for a review with a QR code and a WhatsApp message, and reply to every review.'],
  ['website', 'Get found', 'Does your website load fast on a phone and show up on Google for your main service and town?', 9, 'Create one fast page per service and town, with titles that match what customers search.'],
  ['nap', 'Get found', 'Are your business name, phone and address exactly the same everywhere online?', 4, 'Make your name, address and phone identical on Google, social bios, directories and your website.'],
  ['ai', 'Get found', 'When you ask ChatGPT or Gemini for the best business like yours in your town, are you mentioned?', 4, 'Start GEO: consistent brand facts, schema markup, answer-first content and mentions on trusted Kenyan sites.'],
  ['posting', 'Be seen', 'Do you post on social media at least three times a week, every week?', 8, 'Plan a monthly content calendar and batch-create posts so you never go quiet.'],
  ['video', 'Be seen', 'Do you publish short videos (Reels or TikToks) every month?', 7, 'Film four short videos a month: behind the scenes, before-and-after, price reveal and a customer story.'],
  ['ads', 'Be seen', 'Do you run ads with a clear goal (messages, leads or sales) instead of just boosting posts?', 10, 'Move from “Boost” to Ads Manager with a messages or leads objective, three creatives and a clear offer.'],
  ['reply', 'Convert', 'Do you reply to WhatsApp messages and DMs within an hour during business hours?', 10, 'Set up WhatsApp quick replies and labels, and assign one person to reply within an hour.'],
  ['offer', 'Convert', 'Can customers easily see your prices or offers and pay you by M-Pesa?', 7, 'Show prices or “from” prices, and share your till or paybill in every quick reply.'],
  ['followup', 'Convert', 'Do you follow up with enquiries that did not buy within 48 hours?', 8, 'Label every quoted lead and send a friendly follow-up the next day. This alone lifts sales.'],
  ['tracking', 'Measure', 'Do you know which channel brings most of your sales?', 10, 'Install GA4 and pixels, use separate WhatsApp links per channel, and ask every new customer how they found you.'],
  ['review', 'Measure', 'Do you review leads, cost per lead and sales every month?', 5, 'Hold a 30-minute monthly review of leads, cost per lead and sales, and cut what does not pay.'],
];

export const academy = {
  name: 'Steff Cloud Academy: Digital Marketing for Kenyan Businesses',
  short: 'Free digital marketing course',
  description: 'A free, self-paced course that teaches Kenyan business owners and young marketers how to get found on Google and AI search, grow on social media, run profitable ads and turn chats into sales.',
  hours: 3,
  modules: [
    { title: 'Foundations', outcome: 'Understand how Kenyan customers find and choose businesses online, and set a budget.', lessons: ['digital-marketing-in-kenya-guide', 'digital-marketing-budget-small-business-kenya'], extra: [['Glossary: 44 terms explained', '/learn/digital-marketing-glossary/']] },
    { title: 'Get found on Google & AI', outcome: 'Rank on Google search and Maps, and get mentioned by AI assistants.', lessons: ['seo-for-small-businesses-kenya', 'google-business-profile-nakuru-guide', 'what-is-geo-generative-engine-optimization'] },
    { title: 'Social media & content', outcome: 'Plan a month of content and make short videos that sell.', lessons: ['social-media-content-ideas-kenyan-businesses', 'tiktok-marketing-kenya'] },
    { title: 'Paid advertising', outcome: 'Set budgets, choose objectives and lower your cost per lead.', lessons: ['facebook-instagram-ads-cost-kenya'], extra: [['Tool: Marketing budget calculator', '/tools/marketing-budget-calculator/']] },
    { title: 'Convert, keep & grow', outcome: 'Turn chats into sales, keep customers coming back, and know when to hire help.', lessons: ['whatsapp-business-marketing-kenya', 'how-to-choose-digital-marketing-agency-nakuru'], extra: [['Tool: Digital marketing grader', '/tools/marketing-grader/'], ['Tool: WhatsApp link generator', '/tools/whatsapp-link-generator/']] },
  ],
};
